### PR TITLE
build with cmake

### PR DESCRIPTION
**Pull request by christf**
This allows to build dnrd with cmake which will allow for suitable integration into the openwrt packaging system. Also it allows people to build the code directly from git - the howto in the readme does not work any more

### CODE REVIEW

**Comment by christf** [comment]
well, what do you think? I have no idea how to build this thing with cons but I'd like to add a switch for ipv4 and ipv6 functionality as well as fixing the getopt-part where "-S" is not recognized

**Comment by benjaminpetrin-zz** [comment]
Hey - I appreciate the PR! I know the current build tools are pretty ancient but was working when I last tested. I'll try to test this change in the next day but I would definitely like to merge it!

**Comment by benjaminpetrin-zz** [comment]
Hey @christf, can you help me figure out what I'm doing wrong? I've never used cmake before

```
[bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$git status
On branch christf-cmake
nothing to commit, working directory clean

[bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$cmake .
-- The C compiler identification is AppleClang 7.3.0.7030029
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for usleep
-- Looking for usleep - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bpetrin/Documents/personal/projects/dnrd

[bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$make
Scanning dependencies of target dnrd
[  5%] Building C object CMakeFiles/dnrd.dir/src/args.c.o
[ 11%] Building C object CMakeFiles/dnrd.dir/src/cache.c.o
[ 16%] Building C object CMakeFiles/dnrd.dir/src/check.c.o
[ 22%] Building C object CMakeFiles/dnrd.dir/src/common.c.o
/Users/bpetrin/Documents/personal/projects/dnrd/src/common.c:39:10: fatal error: 'generated/version.h' file not found
#include <generated/version.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/dnrd.dir/src/common.c.o] Error 1
make[1]: *** [CMakeFiles/dnrd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by christf** [comment]
Run make version. That will create the files you are missing.

The default make target should probably include that. I will look for ways to add it and include it in the PR.

Am 27. September 2016 23:33:30 MESZ, schrieb Benjamin Petrin notifications@github.com:

> Hey @christf, can you help me figure out what I'm doing wrong? I've
> never used cmake before
> 
> ```
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$git status
> On branch christf-cmake
> nothing to commit, working directory clean
> 
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$cmake .
> -- The C compiler identification is AppleClang 7.3.0.7030029
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for usleep
> -- Looking for usleep - found
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /Users/bpetrin/Documents/personal/projects/dnrd
> 
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$make
> Scanning dependencies of target dnrd
> [  5%] Building C object CMakeFiles/dnrd.dir/src/args.c.o
> [ 11%] Building C object CMakeFiles/dnrd.dir/src/cache.c.o
> [ 16%] Building C object CMakeFiles/dnrd.dir/src/check.c.o
> [ 22%] Building C object CMakeFiles/dnrd.dir/src/common.c.o
> /Users/bpetrin/Documents/personal/projects/dnrd/src/common.c:39:10:
> fatal error: 'generated/version.h' file not found
> #include <generated/version.h>
>         ^
> 1 error generated.
> make[2]: *** [CMakeFiles/dnrd.dir/src/common.c.o] Error 1
> make[1]: *** [CMakeFiles/dnrd.dir/all] Error 2
> make: *** [all] Error 2
> ```

Viele Grüße

## Christof

Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by christf** [comment]
Also try to build Luke this

Mkdir build
CD build
Cmake ..
Make Version
Make

That way you can delete all build artefacts with RM -RF build

Am 27. September 2016 23:33:30 MESZ, schrieb Benjamin Petrin notifications@github.com:

> Hey @christf, can you help me figure out what I'm doing wrong? I've
> never used cmake before
> 
> ```
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$git status
> On branch christf-cmake
> nothing to commit, working directory clean
> 
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$cmake .
> -- The C compiler identification is AppleClang 7.3.0.7030029
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for usleep
> -- Looking for usleep - found
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /Users/bpetrin/Documents/personal/projects/dnrd
> 
> [bpetrin@mac-2 ~/Documents/personal/projects/dnrd]$make
> Scanning dependencies of target dnrd
> [  5%] Building C object CMakeFiles/dnrd.dir/src/args.c.o
> [ 11%] Building C object CMakeFiles/dnrd.dir/src/cache.c.o
> [ 16%] Building C object CMakeFiles/dnrd.dir/src/check.c.o
> [ 22%] Building C object CMakeFiles/dnrd.dir/src/common.c.o
> /Users/bpetrin/Documents/personal/projects/dnrd/src/common.c:39:10:
> fatal error: 'generated/version.h' file not found
> #include <generated/version.h>
>         ^
> 1 error generated.
> make[2]: *** [CMakeFiles/dnrd.dir/src/common.c.o] Error 1
> make[1]: *** [CMakeFiles/dnrd.dir/all] Error 2
> make: *** [all] Error 2
> ```

Viele Grüße

## Christof

Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by benjaminpetrin-zz** [comment]
Got it, yeah didn't expect that version had to be made first - looks good!

**Comment by christf** [comment]
:-)

**Pull request merged**
